#!/bin/bash
export _IP=$(hostname -I|xargs)

while [[ ${_IP} == "" ]]
do
  sleep 10
  export _IP=$(hostname -I|xargs)
done 

convert -pointsize 50 -fill yellow -draw 'text 130,130 "IP Address: '${_IP}'" ' /home/oracle/bg/oracle-wallpapers.jpg.keep /home/oracle/bg/oracle-wallpapers.jpg
pcmanfm --wallpaper-mode=stretch --set-wallpaper /home/oracle/bg/oracle-wallpapers.jpg
